[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
cnft_fusion = "7xRaTzzgBCXBoGhPL7WxQnkhQBE4VtEYgXu3ezvoQpRq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keypairs/main.json"
